name: JavaScript Tests

# Run on Pull Request to $branch only
on: [push, pull_request]

# Job Setup
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - name: Run ESLint
      run: |
        npm install
        npm run linting

  test:
    needs: linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - name: Run Karma Tests
      run: |
        npm install
        npm run test